const CFG=window.EVENT_CONFIG||{};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(Math.max(0,Math.round(Number(n)||0))).padStart(4,'0');
const PLAYERS_KEY='pertaminaBoothPlayersV3',SCORES_KEY='pertaminaBoothScoresV3',CURRENT_KEY='pertaminaCurrentPlayerV3',WORDS_KEY='pertaminaCustomWordsV3';
let currentPage='home',stream=null,faceMesh=null,faceLoopBusy=false,toastTimer=null;
const imageCache={};

function toast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function readJSON(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function writeJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function uuid(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`}
function toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}

function preloadAssets(){const list=[CFG.splash?.asset,CFG.capture?.truckAsset,CFG.memoryBack,...(CFG.capture?.fuel||[]).map(x=>x.src),...(CFG.capture?.nonFuel||[]).map(x=>x.src),...(CFG.memory||[])];[...new Set(list.filter(Boolean))].forEach(src=>{const im=new Image();im.src=src;imageCache[src]=im})}

function hideSplash(){const s=$('splash');if(!s)return;s.classList.add('splash-hide');setTimeout(()=>{s.remove();if(sessionStorage.getItem('pertaminaBoothAuth')==='1')showApp();else showLogin()},650)}
function showLogin(){$('loginScreen').classList.remove('hidden');$('appRoot').classList.add('hidden');setTimeout(()=>$('loginUser')?.focus(),120)}
function showApp(){$('loginScreen').classList.add('hidden');$('appRoot').classList.remove('hidden');restorePlayerForm();renderWordBank();prepareWordSearch();resetMemory();renderLeaderboard();showPage('home')}
function loginOperator(event){event?.preventDefault();const user=$('loginUser').value.trim().toLowerCase(),pin=$('loginPin').value.trim();if(user===String(CFG.auth?.user||'').toLowerCase()&&pin===String(CFG.auth?.pin||'')){sessionStorage.setItem('pertaminaBoothAuth','1');$('loginError').textContent='';showApp();toast('Booth access granted')}else{$('loginError').textContent='User atau PIN tidak sesuai.';$('loginPin').value='';$('loginPin').focus()}}
function logoutOperator(){if(!confirm('Keluar dari booth operator?'))return;stopAllGames();sessionStorage.removeItem('pertaminaBoothAuth');showLogin()}

function setNavActive(id){document.querySelectorAll('.nav-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.page===id))}
function showPage(id){if(id!==currentPage){if(currentPage==='capture')stopCamera();if(currentPage==='word')stopWordSearch(false);if(currentPage==='memory')stopMemory(false)}currentPage=id;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));setNavActive(id);if(id==='leaderboard')renderLeaderboard();window.scrollTo({top:0,behavior:'smooth'})}
function openGame(id){if(!ensurePlayer())return;if(id==='capture')resetCapture();if(id==='word')prepareWordSearch();if(id==='memory')resetMemory();showPage(id)}
function stopAllGames(){stopCamera();stopWordSearch(false);stopMemory(false)}

function getCurrentPlayerId(){return localStorage.getItem(CURRENT_KEY)||''}
function getCurrentPlayer(){const id=getCurrentPlayerId();return readJSON(PLAYERS_KEY,[]).find(p=>p.id===id)||null}
function restorePlayerForm(){const p=getCurrentPlayer();if(!p)return;$('playerName').value=p.name||'';$('playerSocial').value=p.social||'';$('playerEmail').value=p.email||'';$('playerContact').value=p.contact||'';$('playerStatus').textContent=`Saved • ${p.name}`;$('playerStatus').classList.add('saved')}
function collectPlayerForm(){return{name:$('playerName').value.trim(),social:$('playerSocial').value.trim(),email:$('playerEmail').value.trim(),contact:$('playerContact').value.trim()}}
function validatePlayer(data){if(!data.name){toast('Masukkan nama player terlebih dahulu');$('playerName').focus();return false}if(!data.social&&!data.email&&!data.contact){toast('Isi minimal satu akun sosial, email, atau contact');$('playerSocial').focus();return false}return true}
function registerPlayer(){const data=collectPlayerForm();if(!validatePlayer(data))return false;const players=readJSON(PLAYERS_KEY,[]),current=getCurrentPlayerId(),now=new Date().toISOString();let p=players.find(x=>x.id===current);if(p){Object.assign(p,data,{updatedAt:now})}else{p={id:uuid(),...data,createdAt:now,updatedAt:now};players.push(p);localStorage.setItem(CURRENT_KEY,p.id)}writeJSON(PLAYERS_KEY,players);$('playerStatus').textContent=`Saved • ${p.name}`;$('playerStatus').classList.add('saved');toast('Player data tersimpan');renderLeaderboard();return true}
function ensurePlayer(){const data=collectPlayerForm();if(!validatePlayer(data))return false;const current=getCurrentPlayer();if(!current||current.name!==data.name||current.social!==data.social||current.email!==data.email||current.contact!==data.contact)return registerPlayer();return true}
function newPlayer(){localStorage.removeItem(CURRENT_KEY);['playerName','playerSocial','playerEmail','playerContact'].forEach(id=>$(id).value='');$('playerStatus').textContent='Belum tersimpan';$('playerStatus').classList.remove('saved');$('playerName').focus();toast('Ready for new player')}
function saveScore(game,score){if(!ensurePlayer())return;const p=getCurrentPlayer(),scores=readJSON(SCORES_KEY,[]);scores.push({id:uuid(),playerId:p.id,name:p.name,social:p.social,email:p.email,contact:p.contact,game,score:Math.max(0,Math.round(score||0)),timestamp:new Date().toISOString()});writeJSON(SCORES_KEY,scores);renderLeaderboard()}

// CAPTURE ENERGY — 3 lane head-tracking truck game
const capture={running:false,score:0,time:45,combo:1,objects:[],timer:null,raf:0,lastSpawn:0,roadOffset:0,targetLane:1,truckLane:1,faceX:.5,w:0,h:0,ctx:null};
function resetCapture(){clearInterval(capture.timer);cancelAnimationFrame(capture.raf);Object.assign(capture,{running:false,score:0,time:CFG.capture?.duration||45,combo:1,objects:[],lastSpawn:0,roadOffset:0,targetLane:1,truckLane:1,faceX:.5});$('captureScore').textContent='0000';$('captureTime').textContent=capture.time;$('captureCombo').textContent='x1';$('captureLane').textContent='CENTER';$('captureMeter').style.width='100%';$('trackingState').textContent='STANDBY';$('cameraPrompt').classList.remove('hidden');$('captureResult').classList.add('hidden');resizeCapture()}
async function enableCamera(){if(!ensurePlayer())return;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera unavailable');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});$('webcam').srcObject=stream;await $('webcam').play();initFaceMesh();$('cameraPrompt').classList.add('hidden');await countdown(3);startCaptureRound()}catch(err){$('trackingState').textContent='CAMERA ERROR';toast('Kamera tidak dapat digunakan. Izinkan camera permission dan gunakan HTTPS.') }}
function countdown(n){return new Promise(resolve=>{let i=n;const tick=()=>{if(i<=0){$('captureCountdown').textContent='';resolve();return}$('captureCountdown').textContent=i--;setTimeout(tick,720)};tick()})}
function initFaceMesh(){if(faceMesh||!window.FaceMesh)return;faceMesh=new FaceMesh({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${f}`});faceMesh.setOptions({maxNumFaces:1,refineLandmarks:false,minDetectionConfidence:.55,minTrackingConfidence:.55});faceMesh.onResults(onFaceResults)}
async function processFaceFrame(){if(!capture.running||!stream||!faceMesh)return;if(!faceLoopBusy){faceLoopBusy=true;try{await faceMesh.send({image:$('webcam')})}catch{}faceLoopBusy=false}if(capture.running)requestAnimationFrame(processFaceFrame)}
function onFaceResults(res){if(!capture.running)return;if(!res.multiFaceLandmarks?.length){$('trackingState').textContent='SEARCHING';return}const landmark=res.multiFaceLandmarks[0][1],raw=1-landmark.x;capture.faceX+=(raw-capture.faceX)*.2;capture.targetLane=capture.faceX<.38?0:capture.faceX>.62?2:1;const names=['LEFT','CENTER','RIGHT'];$('captureLane').textContent=names[capture.targetLane];$('trackingState').textContent=`TRACKING • ${names[capture.targetLane]}`}
function startCaptureRound(){capture.running=true;capture.time=CFG.capture?.duration||45;$('trackingState').textContent='SEARCHING';resizeCapture();processFaceFrame();capture.timer=setInterval(()=>{if(!capture.running)return;capture.time--;capture.combo=Math.max(1,capture.combo-.08);$('captureTime').textContent=capture.time;$('captureCombo').textContent='x'+Math.max(1,Math.round(capture.combo));$('captureMeter').style.width=`${Math.max(0,capture.time/(CFG.capture?.duration||45)*100)}%`;if(capture.time<=0)endCapture()},1000);capture.raf=requestAnimationFrame(captureLoop)}
function resizeCapture(){const c=$('captureCanvas');if(!c)return;const r=c.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));capture.ctx=c.getContext('2d');capture.ctx.setTransform(d,0,0,d,0,0);capture.w=r.width;capture.h=r.height}
function roadGeometry(w,h){return{cx:w/2,topW:Math.min(w*.46,560),bottomW:Math.min(w*.92,1040),topY:-10,bottomY:h+8}}
function laneX(road,lane,t){const width=road.topW+(road.bottomW-road.topW)*t,left=road.cx-width/2;return left+width*((lane+.5)/3)}
function boundaryX(road,boundary,t){const width=road.topW+(road.bottomW-road.topW)*t,left=road.cx-width/2;return left+width*(boundary/3)}
function drawRoad(ctx,w,h){const r=roadGeometry(w,h);ctx.fillStyle='#171715';ctx.fillRect(0,0,w,h);const topL=r.cx-r.topW/2,topR=r.cx+r.topW/2,botL=r.cx-r.bottomW/2,botR=r.cx+r.bottomW/2;const grd=ctx.createLinearGradient(0,0,0,h);grd.addColorStop(0,'#343434');grd.addColorStop(.55,'#242424');grd.addColorStop(1,'#151515');ctx.fillStyle=grd;ctx.beginPath();ctx.moveTo(topL,r.topY);ctx.lineTo(topR,r.topY);ctx.lineTo(botR,r.bottomY);ctx.lineTo(botL,r.bottomY);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=2;for(let b=1;b<=2;b++){ctx.beginPath();ctx.moveTo(boundaryX(r,b,0),0);ctx.lineTo(boundaryX(r,b,1),h);ctx.stroke()}capture.roadOffset=(capture.roadOffset+.018)%1;for(let lane=0;lane<3;lane++){for(let k=-1;k<8;k++){const t=((k/7)+capture.roadOffset)%1;if(t<0)continue;const x=laneX(r,lane,t),y=t*h,size=3+8*t;ctx.fillStyle='rgba(255,255,255,.18)';ctx.fillRect(x-size/2,y,size,size*3)}}const lane=capture.targetLane;ctx.fillStyle='rgba(0,112,186,.12)';ctx.beginPath();const a0=boundaryX(r,lane,.70),a1=boundaryX(r,lane+1,.70),b0=boundaryX(r,lane,1),b1=boundaryX(r,lane+1,1);ctx.moveTo(a0,h*.70);ctx.lineTo(a1,h*.70);ctx.lineTo(b1,h);ctx.lineTo(b0,h);ctx.closePath();ctx.fill();return r}
function spawnWave(){const fuel=CFG.capture?.fuel||[],bad=CFG.capture?.nonFuel||[];if(!fuel.length&&!bad.length)return;const lanes=shuffle([0,1,2]),count=Math.random()<.72?2:1;for(let i=0;i<count;i++){const isBad=Math.random()<.34,pool=isBad?bad:fuel,item=pool[Math.floor(Math.random()*pool.length)];capture.objects.push({lane:lanes[i],y:-.09,speed:.0042+Math.random()*.0018,item,bad:isBad,rot:(Math.random()-.5)*.08})}}
function drawGameObject(ctx,o,road){o.y+=o.speed;const t=Math.max(0,Math.min(1,o.y)),x=laneX(road,o.lane,t),y=o.y*capture.h,im=imageCache[o.item.src],size=42+55*t;ctx.save();ctx.translate(x,y);ctx.rotate(o.rot);ctx.shadowColor=o.bad?'rgba(214,25,31,.55)':'rgba(187,215,96,.55)';ctx.shadowBlur=12+10*t;if(im?.complete&&im.naturalWidth){const ratio=im.naturalWidth/im.naturalHeight,h=size,w=h*ratio;ctx.drawImage(im,-w/2,-h/2,w,h)}else{ctx.fillStyle=o.bad?'#D6191F':'#BBD760';ctx.beginPath();ctx.arc(0,0,size*.35,0,Math.PI*2);ctx.fill()}ctx.restore();return{x,y,size}}
function drawTruck(ctx,road){const im=imageCache[CFG.capture?.truckAsset],t=.91;capture.truckLane+=(capture.targetLane-capture.truckLane)*.14;const x=laneX(road,capture.truckLane,t),truckW=Math.min(128,capture.w*.17),ratio=im?.naturalWidth?im.naturalHeight/im.naturalWidth:.55,truckH=truckW*ratio,y=capture.h-truckH-12;ctx.save();ctx.shadowColor='rgba(0,0,0,.65)';ctx.shadowBlur=24;ctx.shadowOffsetY=10;if(im?.complete&&im.naturalWidth)ctx.drawImage(im,x-truckW/2,y,truckW,truckH);else{ctx.fillStyle='#0070BA';ctx.fillRect(x-truckW/2,y,truckW,truckH)}ctx.restore();return{x,y:y+truckH*.5,w:truckW,h:truckH}}
function captureLoop(ts){if(!capture.running)return;const ctx=capture.ctx;if(!ctx){resizeCapture();capture.raf=requestAnimationFrame(captureLoop);return}const w=capture.w,h=capture.h;ctx.clearRect(0,0,w,h);const road=drawRoad(ctx,w,h);if(!capture.lastSpawn||ts-capture.lastSpawn>(CFG.capture?.spawnEvery||820)){spawnWave();capture.lastSpawn=ts}const truck=drawTruck(ctx,road);for(let i=capture.objects.length-1;i>=0;i--){const o=capture.objects[i],p=drawGameObject(ctx,o,road),hit=o.y>.78&&o.y<1.03&&Math.abs(p.x-truck.x)<Math.max(44,truck.w*.48);if(hit){collectCapture(o);capture.objects.splice(i,1)}else if(o.y>1.1)capture.objects.splice(i,1)}capture.raf=requestAnimationFrame(captureLoop)}
function collectCapture(o){const points=Number(o.item.points)||0;if(o.bad){capture.score=Math.max(0,capture.score+points);capture.combo=1;navigator.vibrate?.([35,25,35])}else{capture.score+=Math.round(points*Math.max(1,capture.combo));capture.combo=Math.min(7,capture.combo+.5)}$('captureScore').textContent=pad(capture.score);$('captureCombo').textContent='x'+Math.max(1,Math.round(capture.combo));const flash=$('hitFlash');flash.className=`hit-flash ${o.bad?'bad':'good'}`;setTimeout(()=>flash.className='hit-flash',230)}
function endCapture(){if(!capture.running)return;capture.running=false;clearInterval(capture.timer);cancelAnimationFrame(capture.raf);$('captureResultScore').textContent=pad(capture.score);$('captureResultText').textContent=capture.score>=350?'POWER PLAYER — OUTSTANDING JOURNEY!':capture.score>=180?'GREAT DRIVE — KEEP THE ENERGY MOVING.':'GOOD RUN — TRY ANOTHER JOURNEY.';saveScore('Capture Energy',capture.score);$('captureResult').classList.remove('hidden')}
function restartCapture(){stopCamera();resetCapture();enableCamera()}
function stopCamera(){capture.running=false;clearInterval(capture.timer);cancelAnimationFrame(capture.raf);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if($('webcam'))$('webcam').srcObject=null;faceLoopBusy=false}
window.addEventListener('resize',()=>{if(currentPage==='capture')resizeCapture()});

// ENERGY WORD — reference-style 12x12 word search
const wordState={running:false,size:12,time:120,score:0,found:new Set(),grid:[],placements:{},words:[],timer:null,selecting:false,start:null,preview:[]};
function normalizeWord(s){return String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,16)}
function getCustomWords(){return readJSON(WORDS_KEY,[]).map(normalizeWord).filter(Boolean)}
function getWordBank(){const defaults=(CFG.wordSearch?.defaultWords||[]).map(normalizeWord);return [...new Set([...getCustomWords(),...defaults].filter(w=>w.length>=3&&w.length<=(CFG.wordSearch?.size||12)))]}
function addCustomWord(){const input=$('customWordInput'),word=normalizeWord(input.value);if(word.length<3){toast('Kata minimal 3 karakter');return}let words=getCustomWords();if(words.includes(word)){toast('Kata sudah ada di word bank');return}words.unshift(word);writeJSON(WORDS_KEY,words.slice(0,40));input.value='';renderWordBank();prepareWordSearch();toast(`${word} ditambahkan`)}
function removeCustomWord(word){writeJSON(WORDS_KEY,getCustomWords().filter(w=>w!==word));renderWordBank();prepareWordSearch();toast(`${word} dihapus`)}
function renderWordBank(){const custom=getCustomWords(),bank=getWordBank();$('wordBankList').innerHTML=bank.map(w=>`<span class="word-chip">${esc(w)}${custom.includes(w)?`<button onclick="removeCustomWord('${esc(w)}')" title="Remove">×</button>`:''}</span>`).join('')}
function chooseRoundWords(){const max=CFG.wordSearch?.maxWords||6,custom=getCustomWords(),defaults=shuffle((CFG.wordSearch?.defaultWords||[]).map(normalizeWord));return [...new Set([...custom,...defaults])].filter(w=>w.length>=3&&w.length<=(CFG.wordSearch?.size||12)).slice(0,max)}
function emptyLetterGrid(size){return Array.from({length:size},()=>Array(size).fill(''))}
function tryPlaceWord(grid,word){const size=grid.length,dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]];for(let tries=0;tries<350;tries++){const [dr,dc]=dirs[Math.floor(Math.random()*dirs.length)],r=Math.floor(Math.random()*size),c=Math.floor(Math.random()*size),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||er>=size||ec<0||ec>=size)continue;let ok=true;const cells=[];for(let i=0;i<word.length;i++){const rr=r+dr*i,cc=c+dc*i,ch=grid[rr][cc];if(ch&&ch!==word[i]){ok=false;break}cells.push([rr,cc])}if(!ok)continue;cells.forEach(([rr,cc],i)=>grid[rr][cc]=word[i]);return cells}return null}
function makeWordPuzzle(words,size){const grid=emptyLetterGrid(size),placements={},placed=[];[...words].sort((a,b)=>b.length-a.length).forEach(w=>{const cells=tryPlaceWord(grid,w);if(cells){placements[w]=cells;placed.push(w)}});const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(!grid[r][c])grid[r][c]=letters[Math.floor(Math.random()*letters.length)];return{grid,placements,words:placed}}
function prepareWordSearch(){stopWordSearch(false);const size=CFG.wordSearch?.size||12,puzzle=makeWordPuzzle(chooseRoundWords(),size);Object.assign(wordState,{running:false,size,time:CFG.wordSearch?.duration||120,score:0,found:new Set(),grid:puzzle.grid,placements:puzzle.placements,words:puzzle.words,selecting:false,start:null,preview:[]});$('wordScore').textContent='0';$('wordTime').textContent=`${wordState.time}s`;$('wordFound').textContent='0';$('wordStart').textContent='START GAME';renderWordPuzzle()}
function renderWordPuzzle(){const grid=$('wordGrid');grid.style.gridTemplateColumns=`repeat(${wordState.size},1fr)`;grid.innerHTML=wordState.grid.flatMap((row,r)=>row.map((ch,c)=>`<button class="word-cell" data-r="${r}" data-c="${c}" type="button">${ch}</button>`)).join('');$('wordList').innerHTML=wordState.words.map(w=>`<span data-word="${w}">${esc(w)}</span>`).join('');bindWordPointerEvents()}
function startWordSearch(){if(!ensurePlayer())return;if(wordState.running)return;prepareWordSearch();wordState.running=true;$('wordStart').textContent='PLAYING…';wordState.timer=setInterval(()=>{wordState.time--;$('wordTime').textContent=`${wordState.time}s`;if(wordState.time<=0)finishWordSearch()},1000)}
function bindWordPointerEvents(){const grid=$('wordGrid');if(!grid||grid.dataset.bound==='1')return;grid.dataset.bound='1';grid.addEventListener('pointerdown',e=>{if(!wordState.running)return;const cell=e.target.closest('.word-cell');if(!cell)return;e.preventDefault();wordState.selecting=true;wordState.start={r:+cell.dataset.r,c:+cell.dataset.c};updateWordPreview(wordState.start)});grid.addEventListener('pointermove',e=>{if(!wordState.selecting||!wordState.running)return;e.preventDefault();const cell=document.elementFromPoint(e.clientX,e.clientY)?.closest('.word-cell');if(cell&&grid.contains(cell))updateWordPreview({r:+cell.dataset.r,c:+cell.dataset.c})});window.addEventListener('pointerup',finishWordSelection,{passive:true})}
function lineCells(a,b){if(!a||!b)return[];let dr=b.r-a.r,dc=b.c-a.c;if(dr!==0&&dc!==0&&Math.abs(dr)!==Math.abs(dc))return[];const steps=Math.max(Math.abs(dr),Math.abs(dc)),sr=steps?Math.sign(dr):0,sc=steps?Math.sign(dc):0;return Array.from({length:steps+1},(_,i)=>({r:a.r+sr*i,c:a.c+sc*i}))}
function updateWordPreview(end){document.querySelectorAll('.word-cell.preview').forEach(x=>x.classList.remove('preview'));const cells=lineCells(wordState.start,end);wordState.preview=cells;cells.forEach(({r,c})=>document.querySelector(`.word-cell[data-r="${r}"][data-c="${c}"]`)?.classList.add('preview'))}
function finishWordSelection(){if(!wordState.selecting)return;wordState.selecting=false;const cells=wordState.preview;document.querySelectorAll('.word-cell.preview').forEach(x=>x.classList.remove('preview'));wordState.preview=[];if(!wordState.running||cells.length<2)return;const text=cells.map(({r,c})=>wordState.grid[r][c]).join(''),reverse=[...text].reverse().join(''),match=wordState.words.find(w=>!wordState.found.has(w)&&(w===text||w===reverse));if(!match)return;wordState.found.add(match);cells.forEach(({r,c})=>document.querySelector(`.word-cell[data-r="${r}"][data-c="${c}"]`)?.classList.add('found'));document.querySelector(`#wordList [data-word="${match}"]`)?.classList.add('found');wordState.score+=100+match.length*10;$('wordScore').textContent=wordState.score;$('wordFound').textContent=wordState.found.size;toast(`${match} FOUND +${100+match.length*10}`);if(wordState.found.size===wordState.words.length)finishWordSearch()}
function finishWordSearch(){if(!wordState.running)return;wordState.running=false;clearInterval(wordState.timer);$('wordStart').textContent='PLAY AGAIN';const bonus=wordState.found.size===wordState.words.length?wordState.time*2:0;wordState.score+=bonus;$('wordScore').textContent=wordState.score;saveScore('Energy Word',wordState.score);toast(wordState.found.size===wordState.words.length?`All words found! Bonus +${bonus}`:'Time is up')}
function stopWordSearch(save=false){if(save&&wordState.running)finishWordSearch();else{wordState.running=false;clearInterval(wordState.timer)}}

// ENERGY MEMORY — Pertamina logo card backs
const memoryState={running:false,cards:[],first:null,lock:false,moves:0,matches:0,time:45,timer:null,finished:false};
function resetMemory(){stopMemory(false);Object.assign(memoryState,{running:false,cards:[],first:null,lock:false,moves:0,matches:0,time:45,finished:false});$('memoryMoves').textContent='00';$('memoryMatches').textContent='0';$('memoryTime').textContent='45';$('memoryBoard').innerHTML='';$('memoryResult').classList.add('hidden');$('memoryResult').textContent='';$('memoryStart').textContent='START GAME';renderMemoryPlaceholders()}
function renderMemoryPlaceholders(){const back=CFG.memoryBack||'asset/Pertamina Logo.png';$('memoryBoard').innerHTML=Array.from({length:16},(_,i)=>`<button class="memory-card" type="button" disabled><span class="memory-card-inner"><span class="memory-face memory-back"><img src="${back}" alt="Pertamina Patra Niaga"></span><span class="memory-face memory-front"></span></span></button>`).join('')}
function startMemory(){if(!ensurePlayer())return;stopMemory(false);Object.assign(memoryState,{running:true,cards:shuffle([...(CFG.memory||[]),...(CFG.memory||[])]),first:null,lock:false,moves:0,matches:0,time:45,finished:false});$('memoryMoves').textContent='00';$('memoryMatches').textContent='0';$('memoryTime').textContent='45';$('memoryResult').classList.add('hidden');$('memoryStart').textContent='PLAYING…';const back=CFG.memoryBack||'asset/Pertamina Logo.png';$('memoryBoard').innerHTML=memoryState.cards.map((src,i)=>`<button class="memory-card" data-i="${i}" type="button" onclick="flipMemory(${i})"><span class="memory-card-inner"><span class="memory-face memory-back"><img src="${back}" alt="Pertamina Patra Niaga"></span><span class="memory-face memory-front"><img src="${src}" alt="Pertamina product"></span></span></button>`).join('');memoryState.timer=setInterval(()=>{memoryState.time--;$('memoryTime').textContent=memoryState.time;if(memoryState.time<=0)finishMemory()},1000)}
function flipMemory(i){if(!memoryState.running||memoryState.lock)return;const el=document.querySelector(`.memory-card[data-i="${i}"]`);if(!el||el.classList.contains('flipped')||el.classList.contains('matched'))return;el.classList.add('flipped');if(memoryState.first===null){memoryState.first=i;return}const j=memoryState.first,mate=document.querySelector(`.memory-card[data-i="${j}"]`);memoryState.first=null;memoryState.moves++;$('memoryMoves').textContent=String(memoryState.moves).padStart(2,'0');if(memoryState.cards[i]===memoryState.cards[j]){el.classList.add('matched');mate?.classList.add('matched');memoryState.matches++;$('memoryMatches').textContent=memoryState.matches;if(memoryState.matches===(CFG.memory||[]).length)finishMemory()}else{memoryState.lock=true;setTimeout(()=>{el.classList.remove('flipped');mate?.classList.remove('flipped');memoryState.lock=false},650)}}
function finishMemory(){if(memoryState.finished)return;memoryState.finished=true;memoryState.running=false;clearInterval(memoryState.timer);const total=(CFG.memory||[]).length,score=Math.max(0,memoryState.matches*100+memoryState.time*4-Math.max(0,memoryState.moves-total)*6);saveScore('Energy Memory',score);$('memoryStart').textContent='PLAY AGAIN';$('memoryResult').textContent=`Round complete • ${memoryState.matches}/${total} matches • Score ${score}`;$('memoryResult').classList.remove('hidden')}
function stopMemory(save=false){if(save&&memoryState.running)finishMemory();else{memoryState.running=false;clearInterval(memoryState.timer)}}

function renderLeaderboard(){const scores=readJSON(SCORES_KEY,[]).sort((a,b)=>b.score-a.score),players=readJSON(PLAYERS_KEY,[]);$('playerCount').textContent=players.length;$('scoreCount').textContent=scores.length;$('leaderboardList').innerHTML=scores.length?scores.slice(0,20).map((x,i)=>{const contact=x.social||x.email||x.contact||'—';return`<div class="rank"><span class="num">${String(i+1).padStart(2,'0')}</span><div><span class="name">${esc(x.name)}</span><span class="contact">${esc(contact)}</span></div><span class="game">${esc(x.game)}</span><span class="points">${x.score}</span></div>`}).join(''):'<div class="rank"><span class="num">—</span><div><span class="name">Belum ada score</span><span class="contact">Mulai game untuk mengisi leaderboard.</span></div><span class="game">EVENT BOOTH</span><span class="points">0</span></div>'}
function clearLeaderboard(){if(confirm('Hapus seluruh score leaderboard? Data player tetap disimpan.')){localStorage.removeItem(SCORES_KEY);renderLeaderboard();toast('Leaderboard direset')}}
function exportPlayerData(){const players=readJSON(PLAYERS_KEY,[]),scores=readJSON(SCORES_KEY,[]);if(!players.length){toast('Belum ada data player untuk diekspor');return}if(!window.XLSX){toast('Library Excel belum termuat');return}const playerRows=players.map((p,i)=>({'No':i+1,'Player ID':p.id,'Name':p.name,'Social Media':p.social||'','Email':p.email||'','Contact':p.contact||'','Registered At':p.createdAt||'','Updated At':p.updatedAt||''}));const scoreRows=scores.map((s,i)=>({'No':i+1,'Player ID':s.playerId,'Name':s.name,'Social Media':s.social||'','Email':s.email||'','Contact':s.contact||'','Game':s.game,'Score':s.score,'Played At':s.timestamp||''}));const wb=XLSX.utils.book_new(),wsPlayers=XLSX.utils.json_to_sheet(playerRows),wsScores=XLSX.utils.json_to_sheet(scoreRows.length?scoreRows:[{'No':'','Player ID':'','Name':'','Game':'','Score':'','Played At':''}]);wsPlayers['!cols']=[{wch:6},{wch:20},{wch:24},{wch:24},{wch:28},{wch:20},{wch:24},{wch:24}];wsScores['!cols']=[{wch:6},{wch:20},{wch:24},{wch:24},{wch:28},{wch:20},{wch:22},{wch:12},{wch:24}];XLSX.utils.book_append_sheet(wb,wsPlayers,'Players');XLSX.utils.book_append_sheet(wb,wsScores,'Scores');const d=new Date(),file=`Pertamina_Booth_Player_Data_${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}.xlsx`;XLSX.writeFile(wb,file);toast('Player data downloaded')}

document.addEventListener('DOMContentLoaded',()=>{$('loginForm')?.addEventListener('submit',loginOperator);preloadAssets();renderWordBank();prepareWordSearch();resetMemory();setTimeout(hideSplash,CFG.splash?.duration||2200)});
