const CFG=window.EVENT_CONFIG||{};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(Math.max(0,Math.round(Number(n)||0))).padStart(4,'0');
const PLAYERS_KEY='pertaminaBoothPlayersV4',SCORES_KEY='pertaminaBoothScoresV4',CURRENT_KEY='pertaminaCurrentPlayerV4',WORDS_KEY='pertaminaCustomWordsV4';
let currentPage='home',stream=null,faceMesh=null,faceLoopBusy=false,toastTimer=null;
const imageCache={};

function toast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function readJSON(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function writeJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function uuid(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`}
function toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}
function preloadAssets(){const mem=CFG.memory?.assets||[];const list=[CFG.splash?.asset,CFG.capture?.truckAsset,CFG.memory?.backAsset,...mem,...(CFG.capture?.fuel||[]).map(x=>x.src),...(CFG.capture?.nonFuel||[]).map(x=>x.src)];[...new Set(list.filter(Boolean))].forEach(src=>{const im=new Image();im.src=src;imageCache[src]=im})}

function hideSplash(){const s=$('splash');if(!s)return;s.classList.add('splash-hide');setTimeout(()=>{s.remove();sessionStorage.getItem('pertaminaBoothAuth')==='1'?showApp():showLogin()},760)}
function showLogin(){$('loginScreen')?.classList.remove('hidden');$('appRoot')?.classList.add('hidden');setTimeout(()=>$('loginUser')?.focus(),160)}
function showApp(){$('loginScreen')?.classList.add('hidden');$('appRoot')?.classList.remove('hidden');restorePlayerForm();renderWordBank();prepareWordSearch();resetMemory();renderLeaderboard();showPage('home')}
function loginOperator(event){event?.preventDefault();const user=$('loginUser').value.trim().toLowerCase(),pin=$('loginPin').value.trim();if(user===String(CFG.auth?.user||'').toLowerCase()&&pin===String(CFG.auth?.pin||'')){sessionStorage.setItem('pertaminaBoothAuth','1');$('loginError').textContent='';showApp();toast('Booth access granted')}else{$('loginError').textContent='User atau PIN tidak sesuai.';$('loginPin').value='';$('loginPin').focus()}}
function logoutOperator(){if(!confirm('Keluar dari booth operator?'))return;stopAllGames();sessionStorage.removeItem('pertaminaBoothAuth');showLogin()}

function setNavActive(id){document.querySelectorAll('.nav-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.page===id))}
function showPage(id){if(id!==currentPage){if(currentPage==='capture')stopCamera();if(currentPage==='word')stopWordSearch(false);if(currentPage==='memory')stopMemory(false)}currentPage=id;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));setNavActive(id);if(id==='leaderboard')renderLeaderboard();requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}))}
function openGame(id){if(!ensurePlayer())return;if(id==='capture')resetCapture();if(id==='word')prepareWordSearch();if(id==='memory')resetMemory();showPage(id)}
function stopAllGames(){stopCamera();stopWordSearch(false);stopMemory(false)}

function contactMeta(type){return type==='email'?{label:'EMAIL',placeholder:'nama@email.com',inputType:'email'}:type==='phone'?{label:'WHATSAPP / PHONE',placeholder:'08xx / +62...',inputType:'tel'}:{label:'SOCIAL MEDIA',placeholder:'@username',inputType:'text'}}
function updateContactField(){const type=$('playerContactType')?.value||'social',meta=contactMeta(type),input=$('playerContactValue');if(!input)return;input.placeholder=meta.placeholder;input.type=meta.inputType;input.closest('label').firstChild.nodeValue=`${meta.label}`}
function getCurrentPlayerId(){return localStorage.getItem(CURRENT_KEY)||''}
function getCurrentPlayer(){const id=getCurrentPlayerId();return readJSON(PLAYERS_KEY,[]).find(p=>p.id===id)||null}
function restorePlayerForm(){const p=getCurrentPlayer();if(!p){updateContactField();return}$('playerName').value=p.name||'';$('playerContactType').value=p.contactType||'social';updateContactField();$('playerContactValue').value=p.contactValue||'';$('playerStatus').textContent=`Saved • ${p.name}`;$('playerStatus').classList.add('saved')}
function collectPlayerForm(){return{name:$('playerName').value.trim(),contactType:$('playerContactType').value,contactValue:$('playerContactValue').value.trim()}}
function validatePlayer(data){if(!data.name){toast('Masukkan nama player terlebih dahulu');$('playerName').focus();return false}if(!data.contactValue){toast('Masukkan satu detail kontak player');$('playerContactValue').focus();return false}if(data.contactType==='email'&&!/^\S+@\S+\.\S+$/.test(data.contactValue)){toast('Format email belum sesuai');$('playerContactValue').focus();return false}return true}
function registerPlayer(){const data=collectPlayerForm();if(!validatePlayer(data))return false;const players=readJSON(PLAYERS_KEY,[]),current=getCurrentPlayerId(),now=new Date().toISOString();let p=players.find(x=>x.id===current);if(p){Object.assign(p,data,{updatedAt:now})}else{p={id:uuid(),...data,createdAt:now,updatedAt:now};players.push(p);localStorage.setItem(CURRENT_KEY,p.id)}writeJSON(PLAYERS_KEY,players);$('playerStatus').textContent=`Saved • ${p.name}`;$('playerStatus').classList.add('saved');toast('Player data tersimpan');renderLeaderboard();return true}
function ensurePlayer(){const data=collectPlayerForm();if(!validatePlayer(data))return false;const current=getCurrentPlayer();if(!current||current.name!==data.name||current.contactType!==data.contactType||current.contactValue!==data.contactValue)return registerPlayer();return true}
function newPlayer(){localStorage.removeItem(CURRENT_KEY);$('playerName').value='';$('playerContactType').value='social';$('playerContactValue').value='';updateContactField();$('playerStatus').textContent='Belum tersimpan';$('playerStatus').classList.remove('saved');$('playerName').focus();toast('Ready for new player')}
function saveScore(game,score){if(!ensurePlayer())return;const p=getCurrentPlayer(),scores=readJSON(SCORES_KEY,[]);scores.push({id:uuid(),playerId:p.id,name:p.name,contactType:p.contactType,contactValue:p.contactValue,game,score:Math.max(0,Math.round(score||0)),timestamp:new Date().toISOString()});writeJSON(SCORES_KEY,scores);renderLeaderboard()}

// CAPTURE ENERGY — compact 3-lane truck game
const capture={running:false,score:0,time:45,combo:1,objects:[],timer:null,raf:0,lastSpawn:0,roadOffset:0,targetLane:1,truckLane:1,faceX:.5,w:0,h:0,ctx:null};
function resetCapture(){clearInterval(capture.timer);cancelAnimationFrame(capture.raf);Object.assign(capture,{running:false,score:0,time:CFG.capture?.duration||45,combo:1,objects:[],lastSpawn:0,roadOffset:0,targetLane:1,truckLane:1,faceX:.5});$('captureScore').textContent='0000';$('captureTime').textContent=capture.time;$('captureCombo').textContent='x1';$('captureLane').textContent='CENTER';$('captureMeter').style.width='100%';$('trackingState').textContent='STANDBY';$('cameraPrompt').classList.remove('hidden');$('captureResult').classList.add('hidden');setTimeout(resizeCapture,30)}
async function enableCamera(){if(!ensurePlayer())return;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera unavailable');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});$('webcam').srcObject=stream;await $('webcam').play();initFaceMesh();$('cameraPrompt').classList.add('hidden');await countdown(3);startCaptureRound()}catch(err){$('trackingState').textContent='CAMERA ERROR';toast('Kamera tidak dapat digunakan. Izinkan camera permission dan gunakan HTTPS.')}}
function countdown(n){return new Promise(resolve=>{let i=n;const tick=()=>{if(i<=0){$('captureCountdown').textContent='';resolve();return}$('captureCountdown').textContent=i--;setTimeout(tick,700)};tick()})}
function initFaceMesh(){if(faceMesh||!window.FaceMesh)return;faceMesh=new FaceMesh({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${f}`});faceMesh.setOptions({maxNumFaces:1,refineLandmarks:false,minDetectionConfidence:.55,minTrackingConfidence:.55});faceMesh.onResults(onFaceResults)}
async function processFaceFrame(){if(!capture.running||!stream||!faceMesh)return;if(!faceLoopBusy){faceLoopBusy=true;try{await faceMesh.send({image:$('webcam')})}catch{}faceLoopBusy=false}if(capture.running)requestAnimationFrame(processFaceFrame)}
function onFaceResults(res){if(!capture.running)return;if(!res.multiFaceLandmarks?.length){$('trackingState').textContent='SEARCHING';return}const landmark=res.multiFaceLandmarks[0][1],raw=1-landmark.x;capture.faceX+=(raw-capture.faceX)*.22;capture.targetLane=capture.faceX<.38?0:capture.faceX>.62?2:1;const names=['LEFT','CENTER','RIGHT'];$('captureLane').textContent=names[capture.targetLane];$('trackingState').textContent=`TRACKING • ${names[capture.targetLane]}`}
function startCaptureRound(){capture.running=true;capture.time=CFG.capture?.duration||45;$('trackingState').textContent='SEARCHING';resizeCapture();processFaceFrame();capture.timer=setInterval(()=>{if(!capture.running)return;capture.time--;capture.combo=Math.max(1,capture.combo-.08);$('captureTime').textContent=capture.time;$('captureCombo').textContent='x'+Math.max(1,Math.round(capture.combo));$('captureMeter').style.width=`${Math.max(0,capture.time/(CFG.capture?.duration||45)*100)}%`;if(capture.time<=0)endCapture()},1000);capture.raf=requestAnimationFrame(captureLoop)}
function resizeCapture(){const c=$('captureCanvas');if(!c)return;const r=c.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));capture.ctx=c.getContext('2d');capture.ctx.setTransform(d,0,0,d,0,0);capture.w=r.width;capture.h=r.height}
function roadGeometry(w,h){return{cx:w/2,topW:Math.min(w*.52,520),bottomW:Math.min(w*.88,900),topY:-5,bottomY:h+8}}
function roadWidthAt(road,t){return road.topW+(road.bottomW-road.topW)*t}
function laneX(road,lane,t){const width=roadWidthAt(road,t),left=road.cx-width/2;return left+width*((lane+.5)/3)}
function boundaryX(road,boundary,t){const width=roadWidthAt(road,t),left=road.cx-width/2;return left+width*(boundary/3)}
function laneWidthAt(road,t){return roadWidthAt(road,t)/3}
function drawRoad(ctx,w,h){const r=roadGeometry(w,h);ctx.fillStyle='#0B0A08';ctx.fillRect(0,0,w,h);const topL=r.cx-r.topW/2,topR=r.cx+r.topW/2,botL=r.cx-r.bottomW/2,botR=r.cx+r.bottomW/2;const grd=ctx.createLinearGradient(0,0,0,h);grd.addColorStop(0,'#4b4b4b');grd.addColorStop(.48,'#2c2c2c');grd.addColorStop(1,'#171717');ctx.fillStyle=grd;ctx.beginPath();ctx.moveTo(topL,r.topY);ctx.lineTo(topR,r.topY);ctx.lineTo(botR,r.bottomY);ctx.lineTo(botL,r.bottomY);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=1.6;for(let b=1;b<=2;b++){ctx.beginPath();ctx.moveTo(boundaryX(r,b,0),0);ctx.lineTo(boundaryX(r,b,1),h);ctx.stroke()}capture.roadOffset=(capture.roadOffset+.016)%1;for(let lane=0;lane<3;lane++){for(let k=-1;k<9;k++){const t=((k/8)+capture.roadOffset)%1;if(t<0)continue;const x=laneX(r,lane,t),y=t*h,size=2+5*t;ctx.fillStyle='rgba(255,255,255,.16)';ctx.fillRect(x-size/2,y,size,size*2.6)}}const lane=capture.targetLane;ctx.fillStyle='rgba(0,112,186,.10)';ctx.beginPath();ctx.moveTo(boundaryX(r,lane,.72),h*.72);ctx.lineTo(boundaryX(r,lane+1,.72),h*.72);ctx.lineTo(boundaryX(r,lane+1,1),h);ctx.lineTo(boundaryX(r,lane,1),h);ctx.closePath();ctx.fill();return r}
function spawnWave(){const fuel=CFG.capture?.fuel||[],bad=CFG.capture?.nonFuel||[];if(!fuel.length&&!bad.length)return;const lanes=shuffle([0,1,2]),count=Math.random()<.78?2:1;for(let i=0;i<count;i++){const isBad=Math.random()<(CFG.capture?.nonFuelChance??.34),pool=isBad?bad:fuel,item=pool[Math.floor(Math.random()*pool.length)];capture.objects.push({lane:lanes[i],y:-.10,speed:.0038+Math.random()*.0016,item,bad:isBad,rot:(Math.random()-.5)*.05})}}
function drawGameObject(ctx,o,road){o.y+=o.speed;const t=Math.max(0,Math.min(1,o.y)),x=laneX(road,o.lane,t),y=o.y*capture.h,im=imageCache[o.item.src],laneW=laneWidthAt(road,t),maxW=Math.max(30,laneW*.46),baseH=30+30*t;let drawW=Math.min(maxW,58),drawH=baseH;if(im?.complete&&im.naturalWidth){const ratio=im.naturalWidth/im.naturalHeight;drawW=Math.min(maxW,baseH*ratio);drawH=drawW/ratio}ctx.save();ctx.translate(x,y);ctx.rotate(o.rot);ctx.shadowColor=o.bad?'rgba(214,25,31,.34)':'rgba(187,215,96,.34)';ctx.shadowBlur=8+6*t;if(im?.complete&&im.naturalWidth)ctx.drawImage(im,-drawW/2,-drawH/2,drawW,drawH);else{ctx.fillStyle=o.bad?'#D6191F':'#BBD760';ctx.beginPath();ctx.arc(0,0,Math.min(18,drawW*.28),0,Math.PI*2);ctx.fill()}ctx.restore();return{x,y,w:drawW,h:drawH}}
function drawTruck(ctx,road){const im=imageCache[CFG.capture?.truckAsset],t=.94;capture.truckLane+=(capture.targetLane-capture.truckLane)*.15;const x=laneX(road,capture.truckLane,t),laneW=laneWidthAt(road,t),truckW=Math.min(88,capture.w*.105,laneW*.48),ratio=im?.naturalWidth?im.naturalHeight/im.naturalWidth:.55,truckH=truckW*ratio,y=capture.h-truckH-8;ctx.save();ctx.shadowColor='rgba(0,0,0,.58)';ctx.shadowBlur=15;ctx.shadowOffsetY=7;if(im?.complete&&im.naturalWidth)ctx.drawImage(im,x-truckW/2,y,truckW,truckH);else{ctx.fillStyle='#0070BA';ctx.fillRect(x-truckW/2,y,truckW,truckH)}ctx.restore();return{x,y:y+truckH*.5,w:truckW,h:truckH}}
function captureLoop(ts){if(!capture.running)return;const ctx=capture.ctx;if(!ctx){resizeCapture();capture.raf=requestAnimationFrame(captureLoop);return}const w=capture.w,h=capture.h;ctx.clearRect(0,0,w,h);const road=drawRoad(ctx,w,h);if(!capture.lastSpawn||ts-capture.lastSpawn>(CFG.capture?.spawnEvery||900)){spawnWave();capture.lastSpawn=ts}const truck=drawTruck(ctx,road);for(let i=capture.objects.length-1;i>=0;i--){const o=capture.objects[i],p=drawGameObject(ctx,o,road),sameLane=Math.abs(o.lane-capture.truckLane)<.42,hit=sameLane&&o.y>.84&&o.y<1.04&&Math.abs(p.x-truck.x)<Math.max(26,truck.w*.45);if(hit){collectCapture(o);capture.objects.splice(i,1)}else if(o.y>1.12)capture.objects.splice(i,1)}capture.raf=requestAnimationFrame(captureLoop)}
function collectCapture(o){const points=Number(o.item.points)||0;if(o.bad){capture.score=Math.max(0,capture.score+points);capture.combo=1;navigator.vibrate?.([35,25,35])}else{capture.score+=Math.round(points*Math.max(1,capture.combo));capture.combo=Math.min(7,capture.combo+.5)}$('captureScore').textContent=pad(capture.score);$('captureCombo').textContent='x'+Math.max(1,Math.round(capture.combo));const flash=$('hitFlash');flash.className=`hit-flash ${o.bad?'bad':'good'}`;setTimeout(()=>flash.className='hit-flash',220)}
function endCapture(){if(!capture.running)return;capture.running=false;clearInterval(capture.timer);cancelAnimationFrame(capture.raf);$('captureResultScore').textContent=pad(capture.score);$('captureResultText').textContent=capture.score>=350?'POWER PLAYER — OUTSTANDING JOURNEY!':capture.score>=180?'GREAT DRIVE — KEEP THE ENERGY MOVING.':'GOOD RUN — TRY ANOTHER JOURNEY.';saveScore('Capture Energy',capture.score);$('captureResult').classList.remove('hidden')}
function restartCapture(){stopCamera();resetCapture();enableCamera()}
function stopCamera(){capture.running=false;clearInterval(capture.timer);cancelAnimationFrame(capture.raf);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if($('webcam'))$('webcam').srcObject=null;faceLoopBusy=false}
window.addEventListener('resize',()=>{if(currentPage==='capture')resizeCapture()});

// ENERGY WORD — 12x12 word-search
const wordState={running:false,grid:[],words:[],placements:[],found:new Set(),score:0,time:120,timer:null,dragging:false,start:null,current:[]};
function normalizeWord(v){return String(v||'').toUpperCase().replace(/[^A-Z]/g,'').slice(0,16)}
function getWordBank(){const defaults=CFG.wordSearch?.defaultWords||[],custom=readJSON(WORDS_KEY,[]);return [...new Set([...defaults,...custom].map(normalizeWord).filter(w=>w.length>=3))]}
function renderWordBank(){const custom=readJSON(WORDS_KEY,[]),box=$('wordBankList');if(!box)return;box.innerHTML=custom.length?custom.map(w=>`<span>${esc(w)}<button onclick="removeCustomWord('${esc(w)}')">×</button></span>`).join(''):'<small>Belum ada kata tambahan.</small>'}
function addCustomWord(){const input=$('customWordInput'),w=normalizeWord(input.value);if(w.length<3){toast('Kata minimal 3 huruf');return}const custom=readJSON(WORDS_KEY,[]);if(!custom.includes(w))custom.push(w);writeJSON(WORDS_KEY,custom);input.value='';renderWordBank();prepareWordSearch();toast('Kata ditambahkan')}
function removeCustomWord(w){writeJSON(WORDS_KEY,readJSON(WORDS_KEY,[]).filter(x=>x!==w));renderWordBank();prepareWordSearch()}
function prepareWordSearch(){stopWordSearch(false);const size=CFG.wordSearch?.size||12,bank=getWordBank(),chosen=shuffle(bank).slice(0,Math.min(CFG.wordSearch?.maxWords||6,bank.length));wordState.grid=Array.from({length:size},()=>Array(size).fill(''));wordState.placements=[];wordState.words=[];for(const w of chosen){const placed=placeWord(wordState.grid,w);if(placed){wordState.words.push(w);wordState.placements.push(placed)}}const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(!wordState.grid[r][c])wordState.grid[r][c]=chars[Math.floor(Math.random()*chars.length)];wordState.found=new Set();wordState.score=0;wordState.time=CFG.wordSearch?.duration||120;renderWordGrid();renderWordList();updateWordStats();$('wordStart').disabled=false;$('wordStart').textContent='START GAME'}
function placeWord(grid,word){const n=grid.length,dirs=[[0,1],[1,0],[1,1],[1,-1],[0,-1],[-1,0],[-1,-1],[-1,1]];for(let attempt=0;attempt<220;attempt++){const [dr,dc]=dirs[Math.floor(Math.random()*dirs.length)],r=Math.floor(Math.random()*n),c=Math.floor(Math.random()*n),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||er>=n||ec<0||ec>=n)continue;let ok=true;for(let i=0;i<word.length;i++){const cell=grid[r+dr*i][c+dc*i];if(cell&&cell!==word[i]){ok=false;break}}if(!ok)continue;const cells=[];for(let i=0;i<word.length;i++){const rr=r+dr*i,cc=c+dc*i;grid[rr][cc]=word[i];cells.push(`${rr}-${cc}`)}return{word,cells}}return null}
function renderWordGrid(){const box=$('wordGrid'),n=wordState.grid.length;if(!box)return;box.style.setProperty('--grid-size',n);box.innerHTML=wordState.grid.map((row,r)=>row.map((ch,c)=>`<button class="word-cell" data-r="${r}" data-c="${c}" onpointerdown="wordPointerDown(event,${r},${c})" onpointerenter="wordPointerEnter(event,${r},${c})">${ch}</button>`).join('')).join('')}
function renderWordList(){$('wordList').innerHTML=wordState.words.map(w=>`<span class="${wordState.found.has(w)?'found':''}">${esc(w)}</span>`).join('')}
function updateWordStats(){$('wordScore').textContent=wordState.score;$('wordTime').textContent=`${wordState.time}s`;$('wordFound').textContent=wordState.found.size}
function startWordSearch(){if(!ensurePlayer())return;prepareWordSearch();wordState.running=true;$('wordStart').disabled=true;$('wordStart').textContent='GAME ON';wordState.timer=setInterval(()=>{wordState.time--;updateWordStats();if(wordState.time<=0)finishWordSearch()},1000)}
function lineCells(r1,c1,r2,c2){const dr=Math.sign(r2-r1),dc=Math.sign(c2-c1),rd=Math.abs(r2-r1),cd=Math.abs(c2-c1);if(!(r1===r2||c1===c2||rd===cd))return[];const len=Math.max(rd,cd)+1,cells=[];for(let i=0;i<len;i++)cells.push([r1+dr*i,c1+dc*i]);return cells}
function wordPointerDown(e,r,c){if(!wordState.running)return;e.preventDefault();wordState.dragging=true;wordState.start=[r,c];wordState.current=[[r,c]];renderWordSelection();e.currentTarget.setPointerCapture?.(e.pointerId)}
function wordPointerEnter(e,r,c){if(!wordState.running||!wordState.dragging)return;const cells=lineCells(wordState.start[0],wordState.start[1],r,c);if(cells.length){wordState.current=cells;renderWordSelection()}}
function renderWordSelection(){document.querySelectorAll('.word-cell').forEach(el=>el.classList.remove('selecting'));for(const [r,c] of wordState.current)$('wordGrid')?.querySelector(`[data-r="${r}"][data-c="${c}"]`)?.classList.add('selecting')}
function finishWordDrag(){if(!wordState.dragging)return;wordState.dragging=false;const selected=wordState.current.map(([r,c])=>wordState.grid[r][c]).join(''),reverse=selected.split('').reverse().join(''),match=wordState.words.find(w=>!wordState.found.has(w)&&(w===selected||w===reverse));if(match){wordState.found.add(match);wordState.score+=100+Math.max(0,Math.round(wordState.time*.8));const placement=wordState.placements.find(p=>p.word===match);placement?.cells.forEach(key=>{const [r,c]=key.split('-');$('wordGrid')?.querySelector(`[data-r="${r}"][data-c="${c}"]`)?.classList.add('found')});renderWordList();updateWordStats();toast(`${match} ditemukan`);if(wordState.found.size===wordState.words.length)finishWordSearch()}document.querySelectorAll('.word-cell').forEach(el=>el.classList.remove('selecting'));wordState.current=[]}
function finishWordSearch(){if(!wordState.running)return;wordState.running=false;clearInterval(wordState.timer);if(wordState.found.size===wordState.words.length)wordState.score+=wordState.time*5;updateWordStats();saveScore('Energy Word',wordState.score);$('wordStart').disabled=false;$('wordStart').textContent='PLAY AGAIN';toast(`Energy Word selesai • ${wordState.score} pts`)}
function stopWordSearch(save=false){if(wordState.running&&save)finishWordSearch();else{wordState.running=false;clearInterval(wordState.timer)}wordState.dragging=false}
document.addEventListener('pointerup',finishWordDrag);document.addEventListener('pointercancel',finishWordDrag);

// ENERGY MEMORY — branded cover, asset face
const memoryState={running:false,cards:[],first:null,lock:false,moves:0,matches:0,time:60,timer:null};
function resetMemory(){stopMemory(false);memoryState.cards=[];memoryState.first=null;memoryState.lock=false;memoryState.moves=0;memoryState.matches=0;memoryState.time=CFG.memory?.duration||60;$('memoryMoves').textContent='00';$('memoryMatches').textContent='0';$('memoryTime').textContent=memoryState.time;$('memoryResult').classList.add('hidden');$('memoryResult').innerHTML='';const base=CFG.memory?.assets||[];$('memoryBoard').innerHTML=Array.from({length:base.length*2},(_,i)=>memoryCardMarkup('',i,false)).join('');$('memoryStart').disabled=false;$('memoryStart').textContent='START GAME'}
function memoryCardMarkup(src,i,revealed){const back=CFG.memory?.backAsset||CFG.splash?.asset;return `<button class="memory-card ${revealed?'flipped':''}" data-i="${i}" onclick="flipMemory(${i})"><span class="memory-card-inner"><span class="memory-face memory-cover"><img src="${back}" alt="Pertamina Patra Niaga"></span><span class="memory-face memory-product">${src?`<img src="${src}" alt="Pertamina product">`:''}</span></span></button>`}
function startMemory(){if(!ensurePlayer())return;const base=CFG.memory?.assets||[];memoryState.cards=shuffle([...base,...base]);memoryState.first=null;memoryState.lock=false;memoryState.moves=0;memoryState.matches=0;memoryState.time=CFG.memory?.duration||60;memoryState.running=true;$('memoryMoves').textContent='00';$('memoryMatches').textContent='0';$('memoryTime').textContent=memoryState.time;$('memoryResult').classList.add('hidden');$('memoryBoard').innerHTML=memoryState.cards.map((src,i)=>memoryCardMarkup(src,i,false)).join('');$('memoryStart').disabled=true;$('memoryStart').textContent='GAME ON';clearInterval(memoryState.timer);memoryState.timer=setInterval(()=>{memoryState.time--;$('memoryTime').textContent=memoryState.time;if(memoryState.time<=0)finishMemory()},1000)}
function flipMemory(i){if(!memoryState.running||memoryState.lock)return;const el=document.querySelector(`.memory-card[data-i="${i}"]`);if(!el||el.classList.contains('flipped')||el.classList.contains('matched'))return;el.classList.add('flipped');if(memoryState.first===null){memoryState.first=i;return}const j=memoryState.first;memoryState.first=null;memoryState.moves++;$('memoryMoves').textContent=String(memoryState.moves).padStart(2,'0');const other=document.querySelector(`.memory-card[data-i="${j}"]`);if(memoryState.cards[i]===memoryState.cards[j]){el.classList.add('matched');other?.classList.add('matched');memoryState.matches++;$('memoryMatches').textContent=memoryState.matches;if(memoryState.matches===(CFG.memory?.assets||[]).length)setTimeout(finishMemory,350)}else{memoryState.lock=true;setTimeout(()=>{el.classList.remove('flipped');other?.classList.remove('flipped');memoryState.lock=false},650)}}
function finishMemory(){if(!memoryState.running)return;memoryState.running=false;clearInterval(memoryState.timer);const total=(CFG.memory?.assets||[]).length,score=Math.max(0,memoryState.matches*100+memoryState.time*4-Math.max(0,memoryState.moves-total)*6);saveScore('Energy Memory',score);$('memoryResult').innerHTML=`<b>ROUND COMPLETE</b><strong>${score}</strong><span>${memoryState.matches}/${total} pairs • ${memoryState.moves} moves</span>`;$('memoryResult').classList.remove('hidden');$('memoryStart').disabled=false;$('memoryStart').textContent='PLAY AGAIN'}
function stopMemory(save=false){if(memoryState.running&&save)finishMemory();else{memoryState.running=false;clearInterval(memoryState.timer)}memoryState.lock=false}

function renderLeaderboard(){const players=readJSON(PLAYERS_KEY,[]),scores=readJSON(SCORES_KEY,[]),sorted=[...scores].sort((a,b)=>b.score-a.score);$('playerCount').textContent=players.length;$('scoreCount').textContent=scores.length;$('leaderboardList').innerHTML=sorted.length?sorted.slice(0,20).map((s,i)=>`<div class="leader-row"><span class="rank-no">${String(i+1).padStart(2,'0')}</span><div><b>${esc(s.name)}</b><small>${esc(s.game)} • ${esc(s.contactType||'contact')}</small></div><strong>${s.score}</strong></div>`).join(''):'<div class="empty-state">Belum ada score. Jadilah player pertama.</div>'}
function clearLeaderboard(){if(confirm('Hapus semua score? Data player tetap tersimpan.')){localStorage.removeItem(SCORES_KEY);renderLeaderboard();toast('Scores direset')}}
function exportPlayerData(){const players=readJSON(PLAYERS_KEY,[]),scores=readJSON(SCORES_KEY,[]);if(!window.XLSX){toast('Excel library belum siap');return}const playerRows=players.map(p=>({'Player ID':p.id,'Name':p.name,'Contact Type':p.contactType,'Contact Detail':p.contactValue,'Registered At':p.createdAt,'Updated At':p.updatedAt}));const scoreRows=scores.map(s=>({'Player ID':s.playerId,'Name':s.name,'Contact Type':s.contactType,'Contact Detail':s.contactValue,'Game':s.game,'Score':s.score,'Played At':s.timestamp}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(playerRows),'Players');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(scoreRows),'Scores');const stamp=new Date().toISOString().slice(0,10);XLSX.writeFile(wb,`Pertamina-Booth-Data-${stamp}.xlsx`)}

function init(){preloadAssets();$('loginForm')?.addEventListener('submit',loginOperator);$('customWordInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCustomWord()}});updateContactField();window.addEventListener('load',()=>setTimeout(hideSplash,CFG.splash?.duration||2400))}
init();
