/* Asset integration patch: uses real PNG assets from /asset/ for secondary games. */
(()=>{
  const $=id=>document.getElementById(id);
  let state={cards:[],first:null,lock:false,moves:0,matches:0,time:45,timer:null};
  const base=(window.EVENT_CONFIG&&window.EVENT_CONFIG.memory)||[];
  function cardMarkup(src){return `<img src="${src}" alt="Pertamina product">`;}
  window.resetMemory=function(){clearInterval(state.timer);state={cards:[],first:null,lock:false,moves:0,matches:0,time:45,timer:null};$('memoryBoard').innerHTML='';$('memoryMoves').textContent='00';$('memoryMatches').textContent='0';$('memoryTime').textContent='45';$('memoryStart').style.display='inline-flex'};
  window.startMemory=function(){clearInterval(state.timer);state.cards=[...base,...base].sort(()=>Math.random()-.5);state.first=null;state.lock=false;state.moves=0;state.matches=0;state.time=45;$('memoryStart').style.display='none';$('memoryBoard').innerHTML=state.cards.map((v,i)=>`<button class="memory-card-btn" data-i="${i}" onclick="flipCard(${i})"><span class="memory-back">PG</span></button>`).join('');state.timer=setInterval(()=>{state.time--;$('memoryTime').textContent=state.time;if(state.time<=0)finishMemoryAssets()},1000)};
  window.flipCard=function(i){if(state.lock)return;const el=document.querySelector(`[data-i="${i}"]`);if(!el||el.classList.contains('flipped')||el.classList.contains('matched'))return;el.innerHTML=cardMarkup(state.cards[i]);el.classList.add('flipped');if(state.first===null){state.first=i;return}const j=state.first;state.first=null;state.moves++;$('memoryMoves').textContent=String(state.moves).padStart(2,'0');if(state.cards[i]===state.cards[j]){document.querySelector(`[data-i="${j}"]`)?.classList.add('matched');el.classList.add('matched');state.matches++;$('memoryMatches').textContent=state.matches;if(state.matches===base.length)finishMemoryAssets()}else{state.lock=true;setTimeout(()=>{[i,j].forEach(k=>{const e=document.querySelector(`[data-i="${k}"]`);if(e){e.classList.remove('flipped');e.innerHTML='<span class="memory-back">PG</span>'}});state.lock=false},650)}};
  function finishMemoryAssets(){clearInterval(state.timer);const score=Math.max(0,state.matches*100+state.time*3-Math.max(0,state.moves-base.length)*5);if(typeof window.saveScore==='function')window.saveScore('Energy Memory',score);setTimeout(()=>alert(`Round selesai! Skor: ${score}`),180)}
})();